language: go
sudo: false

branches:
  only:
    - master

env:
  global:
    - HUGO_VERSION=0.53
    - secure: U3UxoXoDYAKYY79xv6J+706BuceAgfY13aca2H/AHhPnP1lUXuseywS0kJZeo5OESGCmxLgYpP6i8N3jIrKPgRmzVDLbZR/MIiT/3DNzVmb6j7jesp7V0YFfHD3VAbN4wIL7XEvl9EA6oqgybINW8+J6pdObBhfOgHM/oEv2a+tPWLRogT2Z8670U/zxoeM2BieqtcqkMkWH+G+JvdSjmPUm/lT6lmtl2KYhjIjLLp3ZvpGzl42fpjAl/v2PSUDvABsI9qxsAz/xOsfHdnWT/QZuglsku7z9CRTDQbpI5yC09mkEy0rg7DiYvH2u8zHssAXOjmgD1RQBtx9aSGmwCZutE+DEPrFXnIstwQMQ2++IL+XsKIYmrnm9QqQW4HAWGliKlv3UFAT0UPUjgNQHWMbWPWg39M+wIWLDr3xObHFY4oFRpIwBfdJ8tKqFLGgNTcqrBGMqE9yCZ2ywqaFYrXqzlhp/4/TS9N6Cpa1zn0yeWzHn+DSPqPujrCmCrjZLI+za5mpGNdPl01ijrA5NZaoU5kGSu8rn4ueQOkm8QwhvucbJ8ozB5BKxYxP3gMnPgXLj4fLbjb+IV38+FpbSX3dNYTcXxvsKBsTZQMBrHY+Y+Itc1aKtZ9MyOmDuXEzncdb87AiXbnNHrLmWFs9PIHWlydhFckEd6hC/PeNruAA=

install: true

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

script:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - git config --global user.email "46429655+S520-BOT@users.noreply.github.com"
  - git config --global user.name "S520-BOT"
  - git checkout translate
  - git branch
  - git merge master
  - hugo -v
  - git add -A -f
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
  - git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git translate
