title = "openBVE Documentation"
theme = "openbve_documentation"
DefaultContentLanguage = "en"
removePathAccents = "true"
publishDir = "public/en"
contentDir = "content/en"

relativeURLs = "true"
uglyURLs = "true"

disableKinds = ["page", "404", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[params]
  logoimage = "/images/logo.png"

[blackfriday]
  hrefTargetBlank = true
  extensions = ["laxHtmlBlocks"]
